# backend/utils/spell_check.py
word_dictionary = {
    'HELO': 'HELLO',
    'THER': 'THERE',
    'WRD': 'WORD',
    'GUD': 'GOOD',
    'MORNNG': 'MORNING',
    # Common misspellings
    'THX': 'THANKS',
    'PLZ': 'PLEASE',
    'U': 'YOU',
    'UR': 'YOUR',
    'R': 'ARE',
    'Y': 'WHY',
    'CUZ': 'BECAUSE',
    'BCUZ': 'BECAUSE',
    'BCZ': 'BECAUSE',
    'DONT': "DON'T",
    'CANT': "CAN'T",
    'WONT': "WON'T",
    'DIDNT': "DIDN'T",
    'ISNT': "ISN'T",
    'WASNT': "WASN'T",
    'WERENT': "WEREN'T",
    'HASNT': "HASN'T",
    'HAVENT': "HAVEN'T",
    'SHOULDNT': "SHOULDN'T",
    'WOULDNT': "WOULDN'T",
    'COULDNT': "COULDN'T",
    
    # Common text shortenings
    'TXT': 'TEXT',
    'MSG': 'MESSAGE',
    'BRB': 'BE RIGHT BACK',
    'GTG': 'GOT TO GO',
    'LOL': 'LAUGHING OUT LOUD',
    'OMG': 'OH MY GOD',
    'IMO': 'IN MY OPINION',
    'IMHO': 'IN MY HUMBLE OPINION',
    'FYI': 'FOR YOUR INFORMATION',
    'ASAP': 'AS SOON AS POSSIBLE',
    
    # Common typos
    'RECIEVE': 'RECEIVE',
    'WIERD': 'WEIRD',
    'DEFINATELY': 'DEFINITELY',
    'SEPERATE': 'SEPARATE',
    'OCCURED': 'OCCURRED',
    'TOMMORROW': 'TOMORROW',
    'ALOT': 'A LOT',
    'THIER': 'THEIR',
    'WICH': 'WHICH',
    'UNTILL': 'UNTIL',
    'BELEIVE': 'BELIEVE',
    'FREIND': 'FRIEND',
    'ACCROSS': 'ACROSS',
    'OCCASSION': 'OCCASION',
    'BUISNESS': 'BUSINESS',
    
    # Common greeting typos
    'HI': 'HI',
    'HIYA': 'HI',
    'HEY': 'HEY',
    'HOWDY': 'HOWDY',
    'EVENIN': 'EVENING',
    'AFTERNON': 'AFTERNOON',
    'AFTRN': 'AFTERNOON',
    'MORN': 'MORNING',
    'NITE': 'NIGHT',
    'GN': 'GOOD NIGHT',
    'GM': 'GOOD MORNING',
    
    # Common word truncations
    'APP': 'APPLICATION',
    'PICS': 'PICTURES',
    'PICS': 'PICTURES',
    'PROB': 'PROBLEM',
    'SEC': 'SECOND',
    'MIN': 'MINUTE',
    'HR': 'HOUR',
    'APPT': 'APPOINTMENT',
    'CONV': 'CONVERSATION',
    'CONVO': 'CONVERSATION',
    'INFO': 'INFORMATION',
    'TEMP': 'TEMPERATURE',
    'ADMIN': 'ADMINISTRATOR',
    'PROF': 'PROFESSOR',
    'TECH': 'TECHNOLOGY',
    'DOCS': 'DOCUMENTS',
}

def correct_spelling(word):
    return word_dictionary.get(word, word)
